name: CI-CD Docker + AKS


on:
push:
branches: [ main ]


jobs:
build-and-deploy:
runs-on: ubuntu-latest


steps:
- name: Checkout repo
uses: actions/checkout@v3


- name: Setup .NET 8 SDK
uses: actions/setup-dotnet@v3
with:
dotnet-version: '8.0.x'


- name: Log in to container registry
uses: docker/login-action@v2
with:
username: ${{ secrets.REGISTRY_USERNAME }}
password: ${{ secrets.REGISTRY_PASSWORD }}


- name: Build Docker image
run: |
docker build -t ${{ secrets.REGISTRY_NAME }}/webapi:latest -f Dockerfile .


- name: Push Docker image
run: |
docker push ${{ secrets.REGISTRY_NAME }}/webapi:latest


- name: Azure Login
uses: azure/login@v1
with:
creds: ${{ secrets.AZURE_CREDENTIALS }}


- name: Get AKS Credentials
run: |
az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }}


- name: Deploy to AKS
run: |
kubectl set image deployment/webapi-deployment webapi=${{ secrets.REGISTRY_NAME }}/webapi:latest -n demo-app
kubectl rollout status deployment/webapi-deployment -n demo-app